name: markets
description: markets
version: 1.7.0
publish_to: none

environment:
  sdk: ">=2.2.2 <3.0.0"

module:
  androidX: true

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.4
  carousel_slider: ^4.0.0
  cached_network_image: ^3.2.0
  google_maps_flutter: ^2.1.1
  google_map_location_picker:
    git:
      url: git://github.com/lyokone/google_map_location_picker.git
  firebase_core: ^1.10.1
  firebase_messaging: ^11.2.0
  flutter_html: ^2.2.0
  flutter_svg: ^0.23.0+1
  flutter_inappwebview: ^5.3.2
  fluttertoast: ^8.0.8
  flutter_staggered_grid_view: ^0.4.1
  global_configuration: ^2.0.0-nullsafety.1
  http: ^0.13.4
  html: ^0.15.0
  intl_utils: ^2.5.1
  intl: ^0.17.0
  location: ^4.3.0
  mvc_pattern: ^8.2.0
  provider: ^6.0.1
  shared_preferences: ^2.0.9
  url_launcher: ^6.0.17
  # google_maps_flutter: 0.5.30
  # google_map_location_picker: 3.3.3
  # global_configuration: 1.5.0
  # http: 0.12.2
  # location: 3.0.2
  # fluttertoast: 4.0.1
  # intl_utils: 1.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# dependency_overrides:
#   intl: ^0.16.1
# provider: ^5.0.0
# google_maps_flutter_platform_interface: ^2.1.2
# plugin_platform_interface: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/cfg/
    - assets/img/

  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/ProductSans-Thin.ttf
          weight: 200
        - asset: assets/fonts/ProductSans-Light.ttf
          weight: 300
        - asset: assets/fonts/ProductSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/ProductSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/ProductSans-Bold.ttf
          weight: 600
        - asset: assets/fonts/ProductSans-Black.ttf
          weight: 700
        - asset: assets/fonts/ProductSans-Black.ttf
          weight: 800
        - asset: assets/fonts/ProductSans-Black.ttf
          weight: 900

flutter_intl:
  enabled: true
